Նախորդ դասերի ընթացքում ծանոթացանք որոշ տարրական ֆունկցիաների հետ, զարգացրեցինք ալգորիթմիկ մտածողությունը։ Սակայն, շատ հաճախ կարիք չի լինում ամեն ինչ զրոյից ծրագրավորելու, քանի որ մի շարք կարևոր ֆունկցիաներ արդեն իսկ հասանելի են այսպես կոչված փաթեթների միջոցով։ Այսօր կծանոթանանք երկու այդպիսի փաթեթի՝ numpy-ի և matplotlib-ի հետ։ Վերջիններս օգտագործվում են մի շարք մաթեմատիկական գործողություններ կատարելու և գրաֆիկներ ստեղծելու համար։ Սկսենք numpy-ից։


In [5]:
import numpy as np # ներմուծել փաթեթն ու ընտրել-np- որպես հապավում, երբեմն կարիք է լինում փաթեթը նախապես ներբեռնել, բայց ոչ մեր դեպքում

## Մաթեմատիկական հաշվարկների հեշտացում

Մինչ այժմ մեկից ավելի արժեքներ պահպանելու համար օգտագործեցինք list-եր։ Վերջիններիս խնդիրներից մեկն այն է, որ մաթեմատիկական գործողություններ կատարելու համար ստիպված էինք օգտագործել ցիկլեր, օրինակ չենք կարող մի գործողությամբ թվեր գումարել լիստի էլեմենտներին ([1,2,3,4]+1 կհանգեցնի սխալի) , իսկ երկու լիստ իրար գումարել փորձելիս ստացվում է հետևյալը ՝ 

In [6]:
list1 = [1,2,3,4]
list2 = [1,1,1,1]
print(list1+list2)

[1, 2, 3, 4, 1, 1, 1, 1]


 Մեր գործը հեշտացնելու են գալիս numpy-ի array-ները։ Դիցուք,
 

In [7]:
array1 = np.array(list1)
array2 = np.array(list2)
print(array1+array2)

[2 3 4 5]


In [8]:
print(np.ones(2))
print(np.zeros(2))
print(np.arange(2,10,2))
print(np.linspace(0,10,5))

[1. 1.]
[0. 0.]
[2 4 6 8]
[ 0.   2.5  5.   7.5 10. ]


Կարող ենք նաև գործողություններ կատարել՝ առանց փոփոխականների տեսակը փոխելու՝

In [9]:
print(np.add(list1,list2))
print(np.add(list1,1)) # np.multiply, np.divide, np.subtract


[2 3 4 5]
[2 3 4 5]


array-ների ինդեքսավորումը կատարվում է նույն կերպ ինչ լիստերի դեպքում՝

In [10]:
print(array1[1])
print(array1[-1])
print(array1[1:3])

2
4
[2 3]


## Տվյալների պահպանում ու ներբեռնում

Մեծ քանակի տվյալների հետ աշխատելու կան ավելի հարմար տարբերակներ, ինչպես օրինակ pandas փաթեթը, սակայն ավելի հեշտ է սկսել numpy array-ներից։ Օրինակ, աշխատավարձերի տվյալները կարող ենք պահպանել հատուկ ֆայլում ամեն անգամ թվերը չմուտքագրելու համար՝ 

In [11]:
old_salaries = [100,120,140,150,160,500,900,1500]
np.save('old_salaries.npy',old_salaries)
 
load = np.load('old_salaries.npy')
print(load)
print(type(load))

[ 100  120  140  150  160  500  900 1500]
<class 'numpy.ndarray'>


Տվյալներ պահպանելիս ու ներբեռնելիս կարևոր է ուշադրություն դարձնել, թե որտեղ են ֆայերը։ Օրինակ, վերևում նշված կոդի դեպքում ֆայլը պահպանվում է այնտեղ, որտեղ գտնվում է կոդի ֆայլը։ Եթե ուզում եք դա փոխել, պետք է համապատասխան փոփոխության ենթարկել path-ը։ Օրինակ՝ 

In [12]:
np.save('../old_salaries.npy',old_salaries) # կոդը պահպանվում է մի թղթապանակ «վերև»

## Մաթեմատիկական գործողություններ՝ մեկ հրամանով

Նախորդ դասին գրեցինք մեր սեփական ֆունկցիաներն օրինակ միջին ու մեդիան հաշվելու համար։ Սա ուներ ուսուցողական նպատակ, իսկ առօրյայում կարող ենք օգտագործել պատրաստի ֆունկցիաներ numpy-ից՝


In [13]:
print(np.mean(list1))
print(np.median(list1))

2.5
2.5


## Demo

In [14]:
old_salaries = np.asarray(old_salaries)
new_salaries = old_salaries+old_salaries*10/100
print(new_salaries)
print(np.mean(new_salaries))
print(np.median(new_salaries))

[ 110.  132.  154.  165.  176.  550.  990. 1650.]
490.875
170.5


## Առաջադրանքներ

Calculating the frequency of values in each bin OR read and explain the code!


In [67]:
old_salaries = [100,120,140,150,160,500,900,1500]
bins = np.linspace(min(old_salaries),max(old_salaries),10)
print(bins)
values = []
for ind,low_lim in enumerate(bins):
    if ind == len(bins)-1:
        upp_lim = np.inf
    else:
        upp_lim = bins[ind+1]
    value = [item for item in old_salaries if low_lim<=item<upp_lim]
    values.append(len(value))
print(values) 

[ 100.          255.55555556  411.11111111  566.66666667  722.22222222
  877.77777778 1033.33333333 1188.88888889 1344.44444444 1500.        ]
[5, 0, 1, 0, 0, 1, 0, 0, 0, 1]
